spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservice-config-hand-dev

---
spring:
  profiles: test
  application:
    name: microservice-config-hand-test 